name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code # 코드 체크아웃 -> master 저장소로 부터 코드를 내려받는다
        uses: actions/checkout@v2

      - name: Set up JDK 17 # Java application 을 실행하는데 필요한 환경 설정 -
        uses: actions/setup-java@v3 # Java 17 환경에서 빌드 , 테스트를 할 수 있게 해준다.
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle # gradle 로 테스트 없이 빌드
        run: ./gradlew build -x test

      - name: Build Docker image # 도커 이미지 빌드
        run: docker build -t leegh963/docker .

      - name: docker login # 도커 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image # 도커 이미지를 도커 허브로 푸시
        run: docker push leegh963/docker

